name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rustc_hash-${{ steps.toolchain.outputs.rustc_hash }}-Cargo.lock_hash-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
